
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='snek-ci',
    version='0.0.1',
    description='A CI/CD for the rest of us',
    python_requires='==3.*,>=3.8.0',
    author='chrisaddy',
    author_email='chris.william.addy@gmail.com',
    license='MIT',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['dagster==0.*,>=0.9.11'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "pytest==6.*,>=6.1.0", "sphinx==3.*,>=3.2.1"]},
)
